In [1]:
import numpy
numpy.__version__

'1.26.4'

In [2]:
import numpy as np

In [4]:
# 단일 타입의 조밀한 배열(dense array)을 만드는 데 사용
import array
L = list(range(10))
# i는 타입 코드
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# numpy는 타입이 다를 경우 상위 타입을 가짐(정수의 상위 타입인 부동 소수점으로 변환)
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
# 타입을 명시적으로 선언
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [7]:
#리스트를 중첩하여 다차원 배열을 초기화
np.array([range(i, i + 3) for i in [2, 4, 6]]) # list comprehenshion

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
# 0으로 채운 길이 10의 정수 배열 만들기
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# 1로 채운 3x5 부동 소수점 배열 만들기
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# 3.14로 채운 3x5 배열 만들기
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# 선형 수열로 채운 배열 만들기
# 0에서 시작해 2씩 더해 20까지 채움
# 내장 함수인 range()와 유사
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
#균등하게 분포된 3x3 배열 만들기
# 0과 1 사이의 난수로 채움
np.random.random((3,3))

array([[0.66467327, 0.46592384, 0.1372639 ],
       [0.06795527, 0.3183497 , 0.69130918],
       [0.6513238 , 0.98971438, 0.89649421]])

In [17]:
# 정규 분포(평균 = 0, 표준 편차 = 1)의 난수로 채운 3x3 배열 만들기
np.random.normal(0, 1, (3, 3))

array([[-0.43966054,  2.52812489, -0.5411724 ],
       [-1.80944453, -0.39962416, -0.7405104 ],
       [ 0.49160159, -0.48974813,  0.87402119]])

In [18]:
# [0, 10] 구간의 임의의 정수로 채운 3x3 배열 만들기
np.random.randint(0, 10, (3, 3))

array([[9, 7, 6],
       [6, 8, 2],
       [3, 9, 9]])

In [19]:
# 3x3 단위 행렬 만들기
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# 세 개의 정수를 가지는 초기화되지 않은 배열 만들기
# 값은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움
np.empty(3)

array([1., 1., 1.])